image: node:10.5.0

pages:
  stage: deploy
  script:
    - ls
    - npm i
    - npm run dev:build
    - mkdir public
    - cp -r dist public
  artifacts:
    paths:
      - public
  only:
    - master