image: node:10.5.0

before_script:
  - apt-get update -qq && apt-get install

pages:
  cache:
    paths:
      - node_modules/
  script:
    - ls
    - npm i
    - npm run dev:build
    - mkdir public
    - mv dist public
    - ls
  artifacts:
    paths:
      - public
  only:
    - master